[player]
	#Level based damage attribute modifier
	# Default: 1.0
	# Range: 0.0 ~ 10.0
	werewolf_damage = 1.0
	#Level based speed attribute modifier
	# Default: 0.1
	# Range: 0.0 ~ 5.0
	werewolf_speed_amount = 0.1
	#Level based armor toughness attribute modifier
	# Default: 3.0
	# Range: 0.0 ~ 10.0
	werewolf_armor_toughness = 3.0
	#Level based claw damage attribute modifier
	# Default: 1.0
	# Range: 0.0 ~ 2.147483647E9
	werewolf_claw_damage = 1.0
	#Cooldown of bite attack (in ticks)
	# Default: 200
	# Range: > 5
	bite_cooldown = 200

	[mobProps.werewolf]
		# Default: 3.0
		# Range: 0.0 ~ 1.7976931348623157E308
		werewolf_attack_damage = 3.0
		# Default: 1.0
		# Range: 0.0 ~ 1.7976931348623157E308
		werewolf_attack_damage_pl = 1.0
		# Default: 30.0
		# Range: 10.0 ~ 1.7976931348623157E308
		werewolf_max_health = 30.0
		# Default: 3.0
		# Range: 0.0 ~ 1.7976931348623157E308
		werewolf_max_health_pl = 3.0
		# Default: 0.3
		# Range: 0.1 ~ 2.0
		werewolf_speed = 0.3
		#Time until a werewolf turns back human
		#In Seconds
		# Default: 25
		# Range: > 10
		werewolf_transform_duration = 25

	[mobProps.human_werewolf]
		# Default: 3.0
		# Range: 0.0 ~ 1.7976931348623157E308
		human_werewolf_attack_damage = 3.0
		# Default: 30.0
		# Range: 10.0 ~ 1.7976931348623157E308
		human_werewolf_max_health = 30.0
		# Default: 0.36
		# Range: 0.1 ~ 2.0
		human_werewolf_speed = 0.36

	[skills.werewolf_form]
		#Time a player can stay in werewolf form
		#In seconds
		# Default: 80
		# Range: > 1
		werewolf_form_time_limit = 80

		[skills.werewolf_form.human_form]
			human_form_enabled = true
			#In seconds
			# Default: 0
			# Range: 0 ~ 10000
			human_form_cooldown = 0
			# Default: 0.05
			# Range: 0.0 ~ 5.0
			human_form_speed_amount = 0.05
			# Default: 4.0
			# Range: 0.0 ~ 20.0
			human_form_armor = 4.0
			# Default: 2.0
			# Range: 0.0 ~ 10.0
			human_form_armor_toughness = 2.0
			# Default: 0.1
			# Range: -1.0 ~ 1.7976931348623157E308
			human_form_food_consumption = 0.1
			# Default: 0.85
			# Range: 0.0 ~ 1.7976931348623157E308
			human_form_food_gain = 0.85

		[skills.werewolf_form.beast_form]
			beast_form_enabled = true
			#In seconds
			# Default: 0
			# Range: 0 ~ 10000
			beast_form_cooldown = 0
			# Default: 0.15
			# Range: 0.0 ~ 5.0
			beast_form_speed_amount = 0.15
			# Default: 2.0
			# Range: 0.0 ~ 100.0
			beast_form_attack_damage = 2.0
			# Default: 16.0
			# Range: 0.0 ~ 20.0
			beast_form_armor = 16.0
			# Default: 8.0
			# Range: 0.0 ~ 10.0
			beast_form_armor_toughness = 8.0
			# Default: 8.0
			# Range: 0.0 ~ 20.0
			beast_form_health = 8.0
			# Default: 6.0
			# Range: 0.0 ~ 1.7976931348623157E308
			beast_form_bite_damage = 6.0
			# Default: 0.3
			# Range: -1.0 ~ 1.7976931348623157E308
			beast_form_food_consumption = 0.3
			# Default: 0.7
			# Range: 0.0 ~ 1.7976931348623157E308
			beast_form_food_gain = 0.7

		[skills.werewolf_form.survival_form]
			survival_form_enabled = true
			#In seconds
			# Default: 0
			# Range: 0 ~ 10000
			survival_form_cooldown = 0
			# Default: 0.5
			# Range: 0.0 ~ 5.0
			survival_form_speed_amount = 0.5
			# Default: 1.5
			# Range: 0.0 ~ 100.0
			survival_form_attack_damage = 1.5
			# Default: 12.8
			# Range: 0.0 ~ 20.0
			survival_form_armor = 12.8
			# Default: 6.0
			# Range: 0.0 ~ 10.0
			survival_form_armor_toughness = 6.0
			# Default: 4.0
			# Range: 0.0 ~ 1.7976931348623157E308
			survival_form_bite_damage = 4.0
			# Default: 4.0
			# Range: 0.0 ~ 1.7976931348623157E308
			survival_form_health = 4.0
			# Default: 0.2
			# Range: -1.0 ~ 1.7976931348623157E308
			survival_form_food_consumption = 0.2
			# Default: 0.77
			# Range: 0.0 ~ 1.7976931348623157E308
			survival_form_food_gain = 0.77

	[skills.howling]
		howling_enabled = true
		# Default: 2.0
		# Range: 0.0 ~ 5.0
		howling_attackspeed_amount = 2.0
		#In seconds
		# Default: 35
		# Range: > 1
		howling_cooldown = 35
		#Howling effect duration
		#In seconds
		# Default: 10
		# Range: > 1
		howling_duration = 10
		#Duration that cancels new howling effects
		#In seconds
		# Default: 10
		# Range: > 1
		howling_disabled_duration = 10

	[skills.bite]
		bite_enabled = true
		#In seconds
		# Default: 5
		# Range: > 0
		bite_cooldown = 5

	[skills.health]
		# Default: 5.0
		# Range: 0.0 ~ 10.0
		health_amount = 5.0

	[skills.health_reg]
		# Default: 0.2
		# Range: 0.0 ~ 1.0
		health_reg_modifier = 0.2

	[skills.resistance]
		# Default: 3.0
		# Range: 0.0 ~ 10.0
		resistance_amount = 3.0

	[skills.speed]
		# Default: 0.013
		# Range: 0.0 ~ 1.0
		speed_amount = 0.013

	[skills.jump]
		# Default: 0.2
		# Range: 0.0 ~ 1.0
		jump_amount = 0.2

	[skills.rage]
		rage_enabled = true
		#The minimum duration
		#In seconds
		# Default: 30
		# Range: > 0
		rage_duration = 30
		#The duration is increased each level by this value
		#In seconds
		# Default: 2
		# Range: > 0
		rage_duration_level_increase = 2
		#In seconds
		# Default: 60
		# Range: > 0
		rage_cooldown = 60
		# Default: 4.0
		# Range: 0.0 ~ 1.7976931348623157E308
		rage_bite_damage = 4.0

	[skills.sense]
		sense_enabled = true
		# Default: 25
		# Range: 1 ~ 400
		sense_radius = 25
		#In seconds
		# Default: 30
		# Range: > 1
		sense_duration = 30
		#In seconds
		# Default: 90
		# Range: > 1
		sense_cooldown = 90

	[skills.stun_bite]
		#In ticks
		# Default: 40
		# Range: > 0
		stun_bite_duration = 40

	[skills.bleeding_bite]
		#In ticks
		# Default: 60
		# Range: > 0
		bleeding_bite_duration = 60

	[skills.better_claws]
		# Default: 1.0
		# Range: 0.0 ~ 2.147483647E9
		better_claw_damage = 1.0

	[skills.fear_action]
		fear_action_enabled = true
		#In seconds
		# Default: 25
		# Range: > 1
		fear_action_cooldown = 25

	[skills.hide_name]
		hide_name_enabled = true
		#In seconds
		# Default: 1
		# Range: > 1
		hide_name_cooldown = 1
		#Intended for unlimited usage
		#In ticks
		# Default: 2147483647
		# Range: > 1
		hide_name_duration = 2147483647

	[skills.leap]
		leap_enabled = true
		#In seconds
		# Default: 6
		# Range: > 1
		leap_cooldown = 6

	[skills.sixth_sense]
		sixth_sense_enabled = true
		#In seconds
		# Default: 30
		# Range: > 1
		sixth_sense_cooldown = 30
		#Intended for unlimited usage
		#In ticks
		# Default: 2147483647
		# Range: > 1
		sixth_sense_duration = 2147483647

	[skills.wolf_pack]
		wolf_pack_enabled = true
		#In seconds
		# Default: 120
		# Range: > 1
		wolf_pack_cooldown = 120
		#In seconds
		# Default: 25
		# Range: > 1
		wolf_pack_wolf_duration = 25
		#Spawned wolves when the wolf pack skill is unlocked
		# Default: 2
		# Range: 0 ~ 10
		wolf_pack_wolf_amount = 2

	[skills."movement tactics"]
		#Doge chance for the movement tactics skill
		# Default: 0.3
		# Range: 0.0 ~ 1.0
		movement_tactics_doge_chance = 0.3

	[skills.thick_fur]
		#Multiplier for the default damage reduction of the werewolf fur
		# Default: 1.5
		# Range: 1.0 ~ 10.0
		thick_fur_multiplier = 1.5

	[skills.efficient_diet]
		#The modifier by which the food consumption is reduced in with the efficient diet skill enabled
		# Default: 0.3
		# Range: 0.0 ~ 1.0
		efficient_diet_food_consumption = 0.3

[potions]
	#How much a Werewolf should be weakened by the silver effect
	# Default: -0.3
	# Range: -1.0 ~ 0.0
	silverStatsReduction = -0.3
	#How much damage the bleeding effect should do per damaging tick
	# Default: 0.4
	# Range: 0.0 ~ 1.7976931348623157E308
	bleedingEffectDamage = 0.4

[util]
	#in seconds
	# Default: 5
	# Range: > 1
	silverBoldEffectDuration = 5
	#The duration of the silver effect when attacking with a silver item
	#in ticks
	# Default: 60
	# Range: > 1
	silverItemEffectDuration = 60
	#if skeletons should ignore werewolves
	skeletonIgnoreWerewolves = true
	#The duration of the silver effect when attacking an entity with silver armor as werewolf per armor item
	#in ticks
	# Default: 5
	# Range: > 0
	silverArmorAttackEffectDuration = 5

[refinements]
	#Increased doge chance for movement tactics skill
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	greater_doge_chance = 0.1
	#Increased wolf spawning for the howling action
	# Default: 1
	# Range: 0 ~ 5
	more_wolves = 1
	#In Seconds
	# Default: 20
	# Range: > 0
	werewolf_form_duration_general_1 = 20
	#In Seconds
	# Default: 40
	# Range: > 0
	werewolf_form_duration_general_2 = 40
	#In Seconds
	# Default: 20
	# Range: > 0
	werewolf_form_duration_survival_1 = 20
	#In Seconds
	# Default: 30
	# Range: > 0
	werewolf_form_duration_survival_2 = 30
	#In Seconds
	# Default: 20
	# Range: > 0
	werewolf_form_duration_beast_1 = 20
	#In Seconds
	# Default: 30
	# Range: > 0
	werewolf_form_duration_beast_2 = 30
	#In Ticks
	# Default: 60
	# Range: > 0
	rage_fury_timer_extend = 60
	#In Ticks
	# Default: 20
	# Range: > 0
	stun_bite_duration_extend = 20

[oils]
	#the amount of hits the oil stays on the weapon
	# Default: 15
	# Range: > 1
	silverOil1Duration = 15
	#the amount of hits the oil stays on the weapon
	# Default: 40
	# Range: > 1
	silverOil2Duration = 40

[blocks]
	#The chunk radius a normal diffusor affects. 0 results in a one chunk area.
	# Default: 1
	# Range: 0 ~ 5
	wolfsbaneDiffuserNormalDist = 1
	#The chunk radius a long diffusor affects. 0 results in a one chunk area.
	# Default: 0
	# Range: 0 ~ 5
	wolfsbaneDiffuserLongDist = 0
	#The chunk radius a improved diffusor affects. 0 results in a one chunk area.
	# Default: 2
	# Range: 0 ~ 5
	wolfsbaneDiffuserImprovedDist = 2
	#The duration in seconds a normal diffusor is active per charge
	# Default: 600
	# Range: > 1
	wolfsbaneDiffuserNormalDuration = 600
	#The duration in seconds a long diffusor is active per charge
	# Default: 1200
	# Range: > 1
	wolfsbaneDiffuserLongDuration = 1200
	#The duration in seconds a improved diffusor is active per charge
	# Default: 600
	# Range: > 1
	wolfsbaneDiffuserImprovedDuration = 600
